src/Entity/Group.php
<?php

namespace App\Entity;

use App\Repository\GroupRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation\Slug;

#[ORM\Entity(repositoryClass: GroupRepository::class)]
#[ORM\Table(name: '`group`')]
class Group
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(type: Types::SMALLINT)]
    private ?int $nbrPlaces = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $creation_date = null;

    #[ORM\Column(nullable: true)]
    private ?bool $restriction_18 = null;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $restriction_lang = null;

    #[ORM\Column(length: 50)]
    private ?string $status = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $imgUrl = null;

    #[ORM\ManyToOne(inversedBy: 'leadedGroups')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $leader = null;

    #[ORM\ManyToOne(inversedBy: 'gameGroups')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Game $game = null;

    #[ORM\Column(nullable: true)]
    private ?bool $restriction_mic = null;

    #[ORM\JoinTable(name: 'membre_group')]
    #[ORM\ManyToMany(targetEntity: User::class, inversedBy: 'groupes')]
    private Collection $members;

    #[ORM\OneToMany(mappedBy: 'groupe', targetEntity: GroupQuestion::class, cascade: ['remove'])]
    private Collection $groupQuestions;

    #[ORM\Column]
    private ?bool $restriction_imgProof = null;

    #[ORM\OneToMany(mappedBy: 'groupe', targetEntity: Candidature::class, cascade: ['remove'])]
    private Collection $candidatures;

    private int $nbrCandidatures;

    #[ORM\ManyToMany(targetEntity: User::class, inversedBy: 'groupsWhereBlackisted')]
    #[ORM\JoinTable(name: 'group_blacklist')]
    private Collection $blacklistedUsers;

    #[ORM\OneToMany(mappedBy: 'team', targetEntity: GroupSession::class, orphanRemoval: true)]
    private Collection $groupSessions;

    // Non mappé: calcul si la team est "active" (= au moins 1 session le mois précédent)
    private bool $active;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $candidature_txt = null;

    #[ORM\Column(length: 100, unique: true)]
    #[Slug(fields: ['title'])]
    private ?string $slug = null;

    public function __construct()
    {
        $this->members = new ArrayCollection();
        $this->groupQuestions = new ArrayCollection();
        $this->candidatures = new ArrayCollection();
        $this->blacklistedUsers = new ArrayCollection();
        $this->groupSessions = new ArrayCollection();
    }

    
    public function __toString() {
        return $this->title;
    }


    public function getId(): ?int
    {
        return $this->id;
    }
    // Fix EasyAdmin:
    public function setId(int $id): self
    {
        $this->id = $id;

        return $this;
    }

    public function isActive(): ?bool
    {
        $lastMonth = (new \DateTime())->modify('-1 month');
    
        foreach ($this->groupSessions as $groupSession) {
            if ($groupSession->getDateStart() >= $lastMonth) {
                return true; 
            }
        }
        return false;
    }


    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getNbrPlaces(): ?int
    {
        return $this->nbrPlaces;
    }

    public function setNbrPlaces(int $nbrPlaces): self
    {
        $this->nbrPlaces = $nbrPlaces;

        return $this;
    }

    public function getCreationDate(): ?\DateTimeInterface
    {
        return $this->creation_date;
    }

    public function setCreationDate(\DateTimeInterface $creation_date): self
    {
        $this->creation_date = $creation_date;

        return $this;
    }

    public function isRestriction18(): ?bool
    {
        return $this->restriction_18;
    }

    public function setRestriction18(?bool $restriction_18): self
    {
        $this->restriction_18 = $restriction_18;

        return $this;
    }

    public function getRestrictionLang(): ?string
    {
        return $this->restriction_lang;
    }

    public function setRestrictionLang(?string $restriction_lang): self
    {
        $this->restriction_lang = $restriction_lang;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getImgUrl(): ?string
    {
        return $this->imgUrl;
    }

    public function setImgUrl(?string $imgUrl): self
    {
        $this->imgUrl = $imgUrl;

        return $this;
    }

    public function getLeader(): ?User
    {
        return $this->leader;
    }

    public function setLeader(?User $leader): self
    {
        $this->leader = $leader;

        return $this;
    }

    public function getGame(): ?Game
    {
        return $this->game;
    }

    public function setGame(?Game $game): self
    {
        $this->game = $game;

        return $this;
    }

    public function isRestrictionMic(): ?bool
    {
        return $this->restriction_mic;
    }

    public function setRestrictionMic(?bool $restriction_mic): self
    {
        $this->restriction_mic = $restriction_mic;

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getMembers(): Collection
    {
        return $this->members;
    }

    public function addMember(User $member): self
    {
        if (!$this->members->contains($member)) {
            $this->members->add($member);
        }

        return $this;
    }

    public function removeMember(User $member): self
    {
        $this->members->removeElement($member);

        return $this;
    }

    /**
     * @return Collection<int, GroupQuestion>
     */
    public function getGroupQuestions(): Collection
    {
        return $this->groupQuestions;
    }

    public function addGroupQuestion(GroupQuestion $groupQuestion): self
    {
        if (!$this->groupQuestions->contains($groupQuestion)) {
            $this->groupQuestions->add($groupQuestion);
            $groupQuestion->setGroupe($this);
        }

        return $this;
    }

    public function removeGroupQuestion(GroupQuestion $groupQuestion): self
    {
        if ($this->groupQuestions->removeElement($groupQuestion)) {
            // set the owning side to null (unless already changed)
            if ($groupQuestion->getGroupe() === $this) {
                $groupQuestion->setGroupe(null);
            }
        }

        return $this;
    }


    public function isRestrictionImgProof(): ?bool
    {
        return $this->restriction_imgProof;
    }

    public function setRestrictionImgProof(bool $restriction_imgProof): self
    {
        $this->restriction_imgProof = $restriction_imgProof;

        return $this;
    }

    /**
     * @return Collection<int, Candidature>
     */
    public function getCandidatures(): Collection
    {
        return $this->candidatures;
    }

    public function addCandidature(Candidature $candidature): self
    {
        if (!$this->candidatures->contains($candidature)) {
            $this->candidatures->add($candidature);
            $candidature->setGroupe($this);
        }

        return $this;
    }

    public function removeCandidature(Candidature $candidature): self
    {
        if ($this->candidatures->removeElement($candidature)) {
            // set the owning side to null (unless already changed)
            if ($candidature->getGroupe() === $this) {
                $candidature->setGroupe(null);
            }
        }

        return $this;
    }

    public function getNbrCandidatures(): int 
    {
        return count($this->candidatures);
    }

    /**
     * @return Collection<int, User>
     */
    public function getBlacklistedUsers(): Collection
    {
        return $this->blacklistedUsers;
    }

    public function addBlacklistedUser(User $blacklistedUser): self
    {
        if (!$this->blacklistedUsers->contains($blacklistedUser)) {
            $this->blacklistedUsers->add($blacklistedUser);
        }

        return $this;
    }

    public function removeBlacklistedUser(User $blacklistedUser): self
    {
        $this->blacklistedUsers->removeElement($blacklistedUser);

        return $this;
    }

    /**
     * @return Collection<int, GroupSession>
     */
    public function getGroupSessions(): Collection
    {
        return $this->groupSessions;
    }

    public function addGroupSession(GroupSession $groupSession): static
    {
        if (!$this->groupSessions->contains($groupSession)) {
            $this->groupSessions->add($groupSession);
            $groupSession->setTeam($this);
        }

        return $this;
    }

    public function removeGroupSession(GroupSession $groupSession): static
    {
        if ($this->groupSessions->removeElement($groupSession)) {
            // set the owning side to null (unless already changed)
            if ($groupSession->getTeam() === $this) {
                $groupSession->setTeam(null);
            }
        }

        return $this;
    }

    public function getCandidatureTxt(): ?string
    {
        return $this->candidature_txt;
    }

src/Form/GroupType.php
<?php

namespace App\Form;

use App\Entity\Censure;
use App\Repository\CensureRepository;
use Symfony\Component\Validator\Context\ExecutionContextInterface;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use App\Entity\Group;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\Callback;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\Range;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Component\Validator\Constraints\Regex;


class GroupType extends AbstractType
{

    public function __construct(private CensureRepository $censureRepository)
    {
    }

    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title', TextType::class, [
                'label' => 'Titre *',
                'required' => true,
                'attr' => [
                    "class" => "form-control",
                    'placeholder' => 'Entrez le nom de la team...',
                ],
                'constraints' => [
                    new Callback([$this, 'validateTextInput']),
                    new NotBlank([
                        'message' => 'Le titre ne peut pas être vide.',
                    ]),
                    new Length([
                        'max' => 250,
                        'maxMessage' => 'Le titre ne peut pas faire plus de 250 caractères.',
                    ]),
                    // Pas de caractères spéciaux (HS bloquant)
                    // new Regex([
                    //     'pattern' => '/^[a-zA-Z0-9-_]+$/',
                    //     'message' => 'Le titre ne doit être composé que de lettres, chiffres et "-" ou "_".',
                    // ]),
                ],
            ])
            ->add('description', TextareaType::class, [
                'label' => 'Description *',
                'required' => true,
                'attr' => [
                    "class" => "form-control",
                    'placeholder' => 'Entrez une présentation de la team...',
                    'rows' => 5
                ],
                'constraints' => [
                    new NotBlank([
                        'message' => 'La description ne peut pas être vide.',
                    ]),
                    new Length([
                        'max' => 1000,
                        'maxMessage' => 'Le description ne peut pas faire plus de 1000 caractères.',
                    ]),
                ],
            ])
            ->add('nbrPlaces', IntegerType::class, [
                'label' => "Places *",
                "required" => false,
                'attr' => [
                    "class" => "form-control nbrPlaceInput",
                    'placeholder' => '3',
                    'value' => '3',
                    'min' => '2',
                    // TODO: A adapter selon jeu:
                    'max' => '6',
                ],
                // TODO: A adapter selon jeu:
                'constraints' => [
                    new Range([
                        'min' => 2,
                        'max' => 6,
                        'minMessage' => 'Le minimum de places est de 2.',
                        'maxMessage' => 'Le nombre de place ne peut pas excéder 6.',
                    ]),
                ],
            ])
            ->add('restriction_18', CheckboxType::class, [
                'label' => "Restriction d'âge",
                'required' => false,
                'attr' => [
                    "class" => "form-check-input",
                ],
            ])
            ->add('restriction_mic', CheckboxType::class, [
                'label' => "Micro obligatoire",
                'required' => false,
                'attr' => [
                    "class" => "form-check-input"
                ],
            ])
            // ->add('restriction_imgProof', CheckboxType::class, [
            //     'label' => "Autoriser pièce jointe: ",
            //     'required' => false,
            //     'attr' => [
            //         "class" => "form-check-input"
            //     ],
            // ])
            // ->add('restriction_lang', ChoiceType::class, [
            //     'label' => 'Langue',
            //     'required' => false,
            //     'choices' => [
            //         'French' => 'fr',
            //         'English' => 'en',
            //         'German' => 'ge',
            //     ],
            //     'placeholder' => '-- Pas de restriction', // Optional: Add a placeholder option
            //     'attr' => [
            //         // "value" => "",
            //         "class" => "form-control",
            //     ],
            // ])
            ->add('status', CheckboxType::class, [
                'label' => "Publique",
                'required' => false,
                'attr' => [
                    "class" => "form-check-input",
                    "checked" => true,
                ],
            ])

            ->add('imgUrl', FileType::class, [
                'label' => 'Illustration de la team:',
                'required' => false, 
                'attr' => ["class" => "form-control"],
                'constraints' => [
                    new File([
                        'maxSize' => '5M', // Maximum file size
                        'mimeTypes' => [
                            'image/png', // Allowed image formats
                            'image/jpeg',
                            'image/jpg',
                            'image/gif',
                        ],
                        'mimeTypesMessage' => 'Please upload a valid image.',
                    ]),
                ],
            ])

            // ajouter logo/img (vérif taille et dimension + aperçu ici)

            // ajouter init Status (si ne pas publier la team tout de suite, default: public)

            ->add('submit', SubmitType::class, [
                'label' => 'Créer',
                'attr' => ["class" => "btn btn-primary"]
            ]);
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Group::class,
        ]);
    }


    public function validateTextInput($value, ExecutionContextInterface $context)
    {
        // Extract words from the entity collection
        $words = $this->extractWordsFromCollection();

        // Convert the text input value to lowercase for case-insensitive comparison
        $lowercaseValue = strtolower($value);

        foreach ($words as $word) {
            if (strpos($lowercaseValue, strtolower($word)) !== false) {
                $context->buildViolation('The word "{{ word }}" is not allowed.')
                    ->setParameter('{{ word }}', $word)
                    ->addViolation();
            }
        }
    }


    private function extractWordsFromCollection(): array
    {
        $censureCollection = $this->censureRepository->findAll();
        $words = [];

        foreach ($censureCollection as $item) {
            if ($item instanceof Censure) {
                $words[] = $item->getWord();
            }
        }

        return $words;
    }
}

templates/group/allGroupList.html.twig
{% extends 'base.html.twig' %}
{# Si USER: n'affiche pas les teams dont l'user est membre #}
{% block title %}Toutes les teams{% endblock %}
{% block meta_description %}
    Parcourez la liste des teams
{% endblock %}

{% block body %}

    <header class="gameHeader" style="background: url('{{ asset('img/banner1.jpg') }}' )">

        <div style="display:inline-flex;">
            <a href="{{ path('app_home') }}"><img src="{{ asset('img/logoSquadForge_v3.png') }}" class="logoPng" id="logoPng" alt='bearded dwarf forging a sword above "SquadForge" title' /></a>
            <a id="logoShrinkTxt" href="{{ path('app_home') }}">SQUADFORGE</a>
        </div>

        <nav id="navLine" class="navLine">
            <span id="closeBurgerMobile"><i class="fa-solid fa-xmark"></i></span>
            <a href="{{ path('app_home') }}" class="homeNav"><i class="fa-solid fa-house"></i></a>
            <a href="{{ path('app_games') }}" class="gamesNav caps">jeux</a>
            {% if app.user %}
                <a href="{{ path('app_userGroups') }}" class="teamsNav caps navActive">teams</a>
                <a href="{{ path('app_showNotifsList') }}" class="notifsNav" style="padding:0;">
                    <div class="navNotifDiv">
                        <i class="fa-solid fa-bell notifBell"></i>
                        {# Bulle newNotifCount si > 0 #}
                        {% if userNotifCount > 0 %}
                            <span class="newNotifBubbleCount bubleNotif" id="newNotifBubbleCount">{{ userNotifCount }}</span>
                        {% endif %}
                    </div>
                </a>
            {% else %}
                <a href="{{ path('app_allGroupList') }}" class="teamsNav caps navActive">teams</a>
            {% endif %}
            {% if app.user and "ROLE_MODO" in app.user.roles %}
            
                <a href="{{ path('app_moderationDashboard') }}" id="modoNav" class="modoNav">
                    <div class="modoNavSubDiv">
                        <span>Modération</span>
                        {% if modoNotifValidationCount > 0 %}
                            <span class="newNotifBubbleCount bubleModo1">{{ modoNotifValidationCount }}</span>
                        {% endif %}
                        {% if modoNotifReportCount > 0 %}
                            <span class="newNotifBubbleCount bubleModo2">{{ modoNotifReportCount }}</span>
                        {% endif %}
                    </div>
                </a>

                <script>
                    // Ajout d'espace libre sur l'onglet Nav "Modération" si bulles (car bulles absolutes)
                    var paddingRightOnglet = 0;
                    if({{modoNotifValidationCount}} > 0) {
                        paddingRightOnglet += 17;
                    }
                    if({{modoNotifReportCount}} > 0) {
                        paddingRightOnglet += 17;
                    }
                    document.getElementById('modoNav').style.paddingRight = paddingRightOnglet + "px";
                </script>

            {% endif %}

            {# Profil + deco #}
            <div id="profilBurgerMobile">
                {% if app.user %}
                    <a href="{{ path('app_user') }}" class="profil" id="profilBtnNav"><i class="fa-solid fa-user profilIcon"></i>  {{ app.user.pseudo|capitalize }}</a>
                    <a href="{{ path('app_logout') }}" class="decoBtn"><i class="fa-solid fa-power-off decoBtnMobile"></i></a>
                {% else %}
                    <a href="{{ path('app_login') }}" class="profil" id="loginBtnNav" style="border-right:2px solid #80808061">Connexion</a>
                    <a href="{{ path('app_register') }}" class="profil" id="registerBtnNav" style="border-bottom-left-radius:0px;">S'inscrire</a>
                {% endif %}
            </div>

        </nav>

        {# Show menu Burger (mobile) #}
        <span id="showBurgerMenu"><i class="fa-solid fa-bars"></i></span>
        
    </header>

    {# HeaderSouligne + Bandeau avertissement muted #}
    {% if app.user and app.user.muted and time_diff_future(app.user.endDateStatus) != false %}
        <div class="headerUnderline"></div>
        <div class="mutedBanner">  
            <span><i class="fa-solid fa-circle-exclamation mutedBannerIcon"></i>Vous êtes actuellement réduit au silence <span class="muteEndDate">( fin dans <span class="strongNbr">{{ time_diff_future(app.user.endDateStatus) }}</span> )</span></span>
        </div>
    {% else %}
        <div class="headerUnderline marginBottomHeaderLine"></div>
    {% endif %}



    <main class="main">

        {# Fil d'Ariane #}
        <p class="breadcrumbs">
            <a  href="{{ path('app_home') }}"><i class="fa-solid fa-house arianeHome"></i></a>
            <i class="fa-solid fa-angle-right arianeArrow"></i>
            <span>Teams</span>
        </p>


        <section>

            <h2 class="pageTitle">Teams</h2>
            {% if app.user %}
                <a href="{{ path('app_userGroups') }}">Mes teams</a>
            {% endif %}
        
            <div class="groupsGrid">

                {% for group in groups %}

                    <a title='"{{ group.title|capitalize }}"' href="{{ path('app_groupDetails', {'groupSlug': group.slug } ) }}" class="teamCardLink" style="width:fit-content;position:relative;">
                        <article class="teamCard" style="border-color:{{ group.game.color }}60">

                            <div class="teamCardTextDiv">

                                <div class="absoluteBg-teamCard" style="background-image:linear-gradient(to top, {{group.game.color}}d6, {{group.game.color}}), url('../img/testMotif2.jpg'); background-size:cover;"></div>

                                <span class="teamCardGameTitle" style="background-color:{{ group.game.color }}">{{ group.game.title }}</span>
                                
                                <p class="teamCardTitleV2">{{ group.title|capitalize }}</p>

                                {% if app.user == group.leader and group.nbrCandidatures > 0 %}
                                    {% if group.nbrCandidatures > 1 %}
                                        <span class="teamCardNbrCandidature">{{ group.nbrCandidatures }} candidatures</span>
                                    {% else %}
                                        <span class="teamCardNbrCandidature">{{ group.nbrCandidatures }} candidature</span>
                                    {% endif %}
                                {% endif %}

                                <div class="teamCard-members">
                                    <i class="fa-solid fa-user-group"></i> 
                                    <span style="position:relative; top:2px;">{{ group.members|length }}/{{ group.nbrPlaces }}</span>
                                </div>

                                <ul class="teamCard-criterias">
                                    <li>
                                        {% if group.restriction18 %}
                                            <img src="{{ asset('img/criteria_18.png') }}" style="filter:invert(0.9);" alt="symbole interdit au moins de 18 ans">
                                        {% else %}
                                            <img src="{{ asset('img/criteria_18.png') }}" style="opacity:0.9;" alt="symbole interdit au moins de 18 ans">
                                        {% endif %}
                                    </li>
                                    <li>
                                        {% if group.restrictionMic %}
                                            <img src="{{ asset('img/criteria_micro.png') }}" style="filter:invert(0.9);" alt="symbole microphone">
                                        {% else %}
                                            <img src="{{ asset('img/criteria_micro.png') }}" style="opacity:0.9;" alt="symbole microphone">
                                        {% endif %}
                                    </li>
                                </ul>
                            
                            </div>

                            <div class="teamCardImgWrapper">
                                {% if group.imgUrl is not null and imageExists(group.imgUrl) %}
                                    <img class="teamCardImg" src="/img/uploads/{{ group.imgUrl }}" alt="image de la team">
                                {% else %}
                                    <img class="teamCardImg" src="/img/teamDefaultPic_dark.jpg" alt="image de team par defaut">
                                {% endif %}

                                {# Label si team active (= au moins 1 session moi précédent) #}
                                {% if group.active %}
                                    <span class="teamCard-isActiveLabel">Active</span>
                                {% endif %}

                                {# Div effet reflet onHover card #}
                                <div class="teamCardReflectDiv"></div>

                                
                            </div>

                        </article>
                    </a>
                    
                {% endfor %}

            </div>

        </section>

    </main>


    {# FadeIn des cards JS #}
    <script>
        var teamCards = document.querySelectorAll('.teamCardLink'); 

        var interval = 160;
        var index = 0;
        
        function applyOpacity() {
            if (index < teamCards.length) {
                teamCards[index].style.opacity = "1";
                index += 1;
                setTimeout(applyOpacity, interval);
            }
        }

        // Délai pour fadeIn du body et header
        setTimeout(() => {
            applyOpacity(); 
        }, 550);
        
    </script>



{% endblock %}