src/Entity/Game.php
<?php

namespace App\Entity;

use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Serializer\Annotation\MaxDepth;

use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;

use App\Repository\GameRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation\Slug;

#[ORM\Entity(repositoryClass: GameRepository::class)]
class Game
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(name: 'id')]
    private ?int $id = null;

    #[ORM\Column(name: 'title', length: 100)]
    private ?string $title = null;

    #[ORM\Column(name: 'editor', length: 100)]
    private ?string $editor = null;

    #[ORM\Column(name: 'publish_date', type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $publish_date = null;

    #[ORM\Column(name: 'description', type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(name: 'color', length: 50)]
    private ?string $color = null;

    #[ORM\ManyToOne(targetEntity: Genre::class, inversedBy: 'games')]
    #[ORM\JoinTable(name: 'genre')]
    #[ORM\JoinColumn(name:'genre_id', referencedColumnName:'id')]
    private ?Genre $genre = null;

    #[ORM\Column(name: 'logo', length: 255, nullable: true)]
    private ?string $logo = null;

    #[ORM\Column(name: 'banner', length: 255, nullable: true)]
    private ?string $banner = null;

    #[ORM\Column(name: 'font_color', length: 50, nullable: true)]
    private ?string $fontColor = null;

    // #[ORM\ManyToMany(targetEntity: User::class, inversedBy: 'favoris')]
    // #[ORM\JoinTable(name: 'favoris')]
    // #[ORM\JoinColumn(name:'user_id', referencedColumnName:'id', nullable: false)]
    // #[ORM\InverseJoinColumn(name:'game_id', referencedColumnName:'id', nullable: false)]
    #[ORM\ManyToMany(targetEntity: User::class, mappedBy: 'favoris')]
    private Collection $favUsers;

    #[ORM\OneToMany(mappedBy: 'game', targetEntity: Topic::class)]
    private Collection $topics;

    #[ORM\Column(name:'tiny_logo', length: 255, nullable: true)]
    private ?string $tinyLogo = null;

    #[ORM\OneToMany(mappedBy: 'game', targetEntity: Notation::class)]
    private Collection $notations;

    #[ORM\OneToMany(mappedBy: 'game', targetEntity: Media::class)]
    private Collection $media;

    #[ORM\Column(name: 'sub_banner', length: 255, nullable: true)]
    private ?string $subBanner = null;

    #[ORM\Column(name: 'sub_banner_mobile', length: 255, nullable: true)]
    private ?string $subBannerMobile = null;

    #[ORM\OneToMany(mappedBy: 'game', targetEntity: Group::class, orphanRemoval: true)]
    private Collection $gameGroups;

    #[ORM\Column(type: Types::SMALLINT)]
    private ?int $nbrPlaces = null;

    #[ORM\Column(name: 'site_logo', length: 255, options: ['default' => "logoSquadForge_v3.png"])]
    private ?string $siteLogo = null;

    #[ORM\Column(nullable: true)]
    private ?bool $showIcon_searchPage = null;

    #[ORM\Column(length: 100, unique: true)]
    #[Slug(fields: ['title'])]
    private ?string $slug = null;


    public function __construct()
    {
        $this->favUsers = new ArrayCollection();
        $this->topics = new ArrayCollection();
        $this->notations = new ArrayCollection();
        $this->media = new ArrayCollection();
        $this->gameGroups = new ArrayCollection();
    }

    
    public function __toString() {
        return $this->title;
    }

    public function getId(): ?int
    {
        return $this->id;
    }
    // Fix EasyAdmin:
    public function setId(int $id): self
    {
        $this->id = $id;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getEditor(): ?string
    {
        return $this->editor;
    }

    public function setEditor(string $editor): self
    {
        $this->editor = $editor;

        return $this;
    }

    public function getPublishDate(): ?\DateTimeInterface
    {
        return $this->publish_date;
    }

    public function setPublishDate(\DateTimeInterface $publish_date): self
    {
        $this->publish_date = $publish_date;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getColor(): ?string
    {
        return $this->color;
    }

    public function setColor(string $color): self
    {
        $this->color = $color;

        return $this;
    }

    public function getGenre(): ?Genre
    {
        return $this->genre;
    }

    public function setGenre(?Genre $genre): self
    {
        $this->genre = $genre;

        return $this;
    }

    public function getLogo(): ?string
    {
        return $this->logo;
    }

    public function setLogo(?string $logo): self
    {
        $this->logo = $logo;

        return $this;
    }

    public function getBanner(): ?string
    {
        return $this->banner;
    }

    public function setBanner(?string $banner): self
    {
        $this->banner = $banner;

        return $this;
    }

    public function getFontColor(): ?string
    {
        return $this->fontColor;
    }

    public function setFontColor(?string $fontColor): self
    {
        $this->fontColor = $fontColor;

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getFavUsers(): Collection
    {
        return $this->favUsers;
    }

    public function addFavUser(User $favUser): self
    {
        if (!$this->favUsers->contains($favUser)) {
            $this->favUsers->add($favUser);
            $favUser->addFavori($this);
        }

        return $this;
    }

    public function removeFavUser(User $favUser): self
    {
        if ($this->favUsers->removeElement($favUser)) {
            $favUser->removeFavori($this);
        }

        return $this;
    }


    // J'ai "raté" ici le nom donné à la fin de la création de la relation ducoup tout remplacé à la mano
    /**
     * @return Collection<int, Topic>
     */
    public function getTopics(): Collection
    {

        return $this->topics;
    }

    // /**
    //  * @return Collection<int, Topic>
    //  */
    // public function getTopicsDesc(): Collection
    // {
    //     // OrderBy PublishDate:

    //     return $this->createQueryBuilder('t')
    //         ->where('t.game = :game')
    //         ->setParameter('game', 1)
    //         ->orderBy('t.publish_date', 'DESC')
    //         ->getQuery()
    //         ->getResult();
    // }

    public function addTopic(Topic $topic): self
    {
        if (!$this->topics->contains($topic)) {
            $this->topics->add($topic);
            $topic->setGame($this);
        }

        return $this;
    }

    public function removeTopic(Topic $topic): self
    {
        if ($this->topics->removeElement($topic)) {
            // set the owning side to null (unless already changed)
            if ($topic->getGame() === $this) {
                $topic->setGame(null);
            }
        }

        return $this;
    }

    public function getTinyLogo(): ?string
    {
        return $this->tinyLogo;
    }

    public function setTinyLogo(?string $tinyLogo): self
    {
        $this->tinyLogo = $tinyLogo;

        return $this;
    }

    /**
     * @return Collection<int, Notation>
     */
    public function getNotations(): Collection
    {
        return $this->notations;
    }

    public function addNotation(Notation $notation): self
    {
        if (!$this->notations->contains($notation)) {
            $this->notations->add($notation);
            $notation->setGame($this);
        }

        return $this;
    }

    public function removeNotation(Notation $notation): self
    {
        if ($this->notations->removeElement($notation)) {
            // set the owning side to null (unless already changed)
            if ($notation->getGame() === $this) {
                $notation->setGame(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Media>
     */
    public function getMedia(): Collection
    {
        return $this->media;
    }

    public function addMedium(Media $medium): self
    {
        if (!$this->media->contains($medium)) {
            $this->media->add($medium);
            $medium->setGame($this);
        }

        return $this;
    }

    public function removeMedium(Media $medium): self
    {
        if ($this->media->removeElement($medium)) {
            // set the owning side to null (unless already changed)
            if ($medium->getGame() === $this) {
                $medium->setGame(null);
            }
        }

        return $this;
    }

    public function getSubBanner(): ?string
    {
        return $this->subBanner;
    }

    public function setSubBanner(?string $subBanner): self
    {
        $this->subBanner = $subBanner;

        return $this;
    }

    /**
     * @return Collection<int, Group>
     */
    public function getGameGroups(): Collection
    {
        return $this->gameGroups;
    }

    public function addGameGroup(Group $gameGroup): self
    {
        if (!$this->gameGroups->contains($gameGroup)) {
            $this->gameGroups->add($gameGroup);
            $gameGroup->setGame($this);
        }

        return $this;
    }

    public function removeGameGroup(Group $gameGroup): self
    {
        if ($this->gameGroups->removeElement($gameGroup)) {
            // set the owning side to null (unless already changed)
            if ($gameGroup->getGame() === $this) {

src/Entity/Report.php
<?php

namespace App\Entity;

use App\Repository\ReportRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ReportRepository::class)]
class Report
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'reports')]
    private ?User $user_reporter = null;

    #[ORM\Column]
    private ?int $objectId = null;

    #[ORM\Column(length: 50)]
    private ?string $objectType = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $creation_date = null;

    #[ORM\ManyToOne(inversedBy: 'reports')]
    #[ORM\JoinColumn(nullable: false)]
    private ?ReportMotif $reportMotif = null;

    
    public function __toString() {
        return $this->id;
    }

    public function getId(): ?int
    {
        return $this->id;
    }
    // Fix EasyAdmin:
    public function setId(int $id): self
    {
        $this->id = $id;

        return $this;
    }

    public function getUserReporter(): ?User
    {
        return $this->user_reporter;
    }

    public function setUserReporter(?User $user_reporter): self
    {
        $this->user_reporter = $user_reporter;

        return $this;
    }

    public function getObjectId(): ?int
    {
        return $this->objectId;
    }

    public function setObjectId(int $objectId): self
    {
        $this->objectId = $objectId;

        return $this;
    }

    public function getObjectType(): ?string
    {
        return $this->objectType;
    }

    public function setObjectType(string $objectType): self
    {
        $this->objectType = $objectType;

        return $this;
    }

    public function getCreationDate(): ?\DateTimeInterface
    {
        return $this->creation_date;
    }

    public function setCreationDate(\DateTimeInterface $creation_date): self
    {
        $this->creation_date = $creation_date;

        return $this;
    }

    public function getReportMotif(): ?ReportMotif
    {
        return $this->reportMotif;
    }

    public function setReportMotif(?ReportMotif $reportMotif): self
    {
        $this->reportMotif = $reportMotif;

        return $this;
    }
}

templates/moderation/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Profil utilisateur{% endblock %}

{% block body %}

    
    <header class="globalBanner" style="background: url('{{ asset('img/banner.jpg') }}' )">
        <a href="{{ path('app_home') }}"><img src="{{ asset('img/logoSquadForge_White_Rogned.png') }}" class="logoPng" /></a>
        <nav class="navLine">
            <a href="{{ path('app_games') }}">JEUX</a>
            {% if app.user %}
                <a href="{{ path('app_userGroups') }}" style="white;">TEAMS</a>
                <a href="{{ path('app_showNotifsList') }}">
                    <div style="position:relative; margin-right:10px;">
                        <i class="fa-solid fa-bell notifBell"></i>
                        {# Bulle newNotifCount si > 0#}
                        {% if userNotifCount > 0 %}
                            <span class="newNotifBubbleCount" id="newNotifBubbleCount">{{ userNotifCount }}</span>
                        {% endif %}
                    </div>
                </a>
            {% endif %}
            {% if app.user and "ROLE_MODO" in app.user.roles %}
                <a href="{{ path('app_moderationDashboard') }}">
                    <div style="position:relative; margin-right:10px;">
                        <span>Modération</span>
                        {% if modoNotifCount > 0 %}
                            <span class="newNotifBubbleCount">{{ modoNotifCount }}</span>
                        {% endif %}
                    </div>
                </a>
            {% endif %}
        </nav>
    </header>
    <div class="headerUnderline"></div>



    <div class="main">


        <h2>Espace Modération</h2>


        <div class="sectionContainer modoSection" >

            <h3>Topics en attente</h3>

            {% if lastWaitingTopics|length == 0 %}

                <p class="emptyListMsg">Aucun topic en attente de validation</p>
                
            {% else %}
                        
                {% for topic in lastWaitingTopics %}

                    <div id="topicCard{{ topic.id }}" class="topicCard" style="border-bottom: 4px solid {{ topic.game.color }}; cursor:pointer;">
                        <img class="tinyLogo" src="{{ asset('img/games/tinyLogo/' ~ topic.game.tinyLogo) }}" />
                        <span id="topicTitle{{ topic.id }}" class="topicTitle">{{ topic.title|capitalize }}</span>
                        <span>{{ topic.validated }}</span>
                        <span class="topicCardAuthor">{{ topic.user.pseudo }}</span>
                        <span class="topicCardPublishDate">{{ time_diff(topic.publishDate) }}</span>
                        {% if topic.topicPostsCount == 0 %}
                            <span style="opacity:0.5;">{{ topic.topicPostsCount }} <i class="fa-solid fa-message" style="color:grey;"></i></span>
                        {% else %}
                            <span>{{ topic.topicPostsCount }} <i class="fa-solid fa-message" style="color:{{ topic.game.color }}"></i></span>
                        {% endif %}
                    </div>
                    <div id="topicSubCard{{ topic.id }}" class="topicSubCard notDisplayed">
                        <p>{{ topic.firstMsg }}</p>
                        <div class="mediaApprovalLine">
                            <a href="{{ path('app_validateTopic', {'id': topic.id}) }}">
                                <span class="mediaApproveBtn"><i class="fa-solid fa-check"></i></span>
                            </a>
                            <a href="{{ path('app_refuseTopic', {'id': topic.id}) }}">
                                <span class="mediaRefuseBtn"><i class="fa-solid fa-xmark"></i></span>
                            </a>
                        </div>

                    </div>

                    {# OnClick TopicCard: détails et boutons validation/refus #}
                    <script>
                        document.getElementById('topicCard{{ topic.id }}').addEventListener('click', function() {
                            document.getElementById('topicSubCard{{ topic.id }}').classList.toggle('notDisplayed');
                        });
                    </script>
                {% endfor %}
            {% endif %} 
        </div>




        <div class="sectionContainer modoSection" >

            <h3>Médias en attente</h3>

            {% if lastWaitingMedias|length == 0 %}

                <p class="emptyListMsg">Aucun média en attente de validation</p>

            {% else %}

                <div class="listContainer marginTop mediaList">

                    {% for media in lastWaitingMedias %}

                        <div id="mediaCard{{ media.id }}" class="mediaCard" style="cursor:pointer;">
                            <div class="mediaCardHeader" style="border-bottom: 4px solid {{ media.game.color }}">
                                <img class="tinyLogo" src="{{ asset('img/games/tinyLogo/' ~ media.game.tinyLogo) }}" />
                                <span id="mediaCardTitle{{ media.id }}" class="mediaTitle" style="font-family:'K2D',sans-serif;">{{ media.title|capitalize }}</span>
                                <span id="topicStatusValidate{{ media.id }}">{{ media.validated }}</span>
                                {# <span>{{ media.user.pseudo }}</span> #}
                                <span class="topicCardPublishDate">{{ time_diff(media.publishDate) }}</span>
                            </div>
                            <img src="{{ asset("img/uploads/" ~ media.url) }}" alt="media" class="mediaImg" />
                        </div>

                        <div id="mediaSubCard{{ media.id }}" class="mediaApprovalLine notDisplayed">
                            <a href="{{ path('app_validateMedia', {'id': media.id}) }}">
                                <span class="mediaApproveBtn"><i class="fa-solid fa-check"></i></span>
                            </a>
                            <a href="{{ path('app_refuseMedia', {'id': media.id}) }}">
                                <span class="mediaRefuseBtn"><i class="fa-solid fa-xmark"></i></span>
                            </a>
                        </div>

                        {# OnClick MediaCard: détails et boutons validation/refus #}
                        <script>
                            document.getElementById('mediaCard{{ media.id }}').addEventListener('click', function() {
                                document.getElementById('mediaSubCard{{ media.id }}').classList.toggle('notDisplayed');
                                document.getElementById('mediaCard{{ media.id }}').classList.toggle('mediaCard');
                                document.getElementById('mediaCardTitle{{ media.id }}').classList.toggle('mediaTitle');
                                document.getElementById('topicStatusValidate{{ media.id }}').classList.toggle('mediaStatusValidate');
                            });
                        </script>

                    {% endfor %}
                </div>
            {% endif %}
        </div>






        <div class="sectionContainer modoSection" >
            <h3>Signalements</h3>

            <div class="reportsDiv">
                {% for report in reports %}
                    <span>{{ report.reportMotif.text }}, type: {{ report.objectType }}, ancienneté: {{ time_diff(report.creationDate) }} </span>
                {% endfor %}
            </div>

        </div>








        <div class="sectionContainer modoSection" >

            <h3>Mots censurés</h3>
            
            <div class="censuredWordsList">
                {% for censureWord in censureWords %}
                    <div style="display:inline-flex; justify-content:space-around; padding: 5px 0; border-bottom:1px solid rgba(255,255,255,0.2);">
                        <span style="width:100px;">"{{ censureWord.word }}"</span>
                        <span style="width:100px;">{{ time_diff(censureWord.creationDate) }}</span>
                        <pspan style="width:100px;">par {{ censureWord.user.pseudo }}</span>
                        <a href="{{ path('app_deleteCensure', {'id': censureWord.id }) }}">
                            <i class="fa-solid fa-xmark"></i>
                        </a>
                    </div>
                {% endfor %}

            </div>

            {{ form_start(formAddCensoredWord) }}
                <div class="inline" style="position:relative; margin: 5px auto;">
                    {{ form_widget(formAddCensoredWord.word) }} 
                    {{ form_widget(formAddCensoredWord.submit) }}
                </div>
            {{ form_end(formAddCensoredWord) }}

        </div>



        

        








    </div>

{% endblock %}