src/Entity/Game.php
<?php

namespace App\Entity;

use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Serializer\Annotation\MaxDepth;

use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;

use App\Repository\GameRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation\Slug;

#[ORM\Entity(repositoryClass: GameRepository::class)]
class Game
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(name: 'id')]
    private ?int $id = null;

    #[ORM\Column(name: 'title', length: 100)]
    private ?string $title = null;

    #[ORM\Column(name: 'editor', length: 100)]
    private ?string $editor = null;

    #[ORM\Column(name: 'publish_date', type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $publish_date = null;

    #[ORM\Column(name: 'description', type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(name: 'color', length: 50)]
    private ?string $color = null;

    #[ORM\ManyToOne(targetEntity: Genre::class, inversedBy: 'games')]
    #[ORM\JoinTable(name: 'genre')]
    #[ORM\JoinColumn(name:'genre_id', referencedColumnName:'id')]
    private ?Genre $genre = null;

    #[ORM\Column(name: 'logo', length: 255, nullable: true)]
    private ?string $logo = null;

    #[ORM\Column(name: 'banner', length: 255, nullable: true)]
    private ?string $banner = null;

    #[ORM\Column(name: 'font_color', length: 50, nullable: true)]
    private ?string $fontColor = null;

    // #[ORM\ManyToMany(targetEntity: User::class, inversedBy: 'favoris')]
    // #[ORM\JoinTable(name: 'favoris')]
    // #[ORM\JoinColumn(name:'user_id', referencedColumnName:'id', nullable: false)]
    // #[ORM\InverseJoinColumn(name:'game_id', referencedColumnName:'id', nullable: false)]
    #[ORM\ManyToMany(targetEntity: User::class, mappedBy: 'favoris')]
    private Collection $favUsers;

    #[ORM\OneToMany(mappedBy: 'game', targetEntity: Topic::class)]
    private Collection $topics;

    #[ORM\Column(name:'tiny_logo', length: 255, nullable: true)]
    private ?string $tinyLogo = null;

    #[ORM\OneToMany(mappedBy: 'game', targetEntity: Notation::class)]
    private Collection $notations;

    #[ORM\OneToMany(mappedBy: 'game', targetEntity: Media::class)]
    private Collection $media;

    #[ORM\Column(name: 'sub_banner', length: 255, nullable: true)]
    private ?string $subBanner = null;

    #[ORM\Column(name: 'sub_banner_mobile', length: 255, nullable: true)]
    private ?string $subBannerMobile = null;

    #[ORM\OneToMany(mappedBy: 'game', targetEntity: Group::class, orphanRemoval: true)]
    private Collection $gameGroups;

    #[ORM\Column(type: Types::SMALLINT)]
    private ?int $nbrPlaces = null;

    #[ORM\Column(name: 'site_logo', length: 255, options: ['default' => "logoSquadForge_v3.png"])]
    private ?string $siteLogo = null;

    #[ORM\Column(nullable: true)]
    private ?bool $showIcon_searchPage = null;

    #[ORM\Column(length: 100, unique: true)]
    #[Slug(fields: ['title'])]
    private ?string $slug = null;


    public function __construct()
    {
        $this->favUsers = new ArrayCollection();
        $this->topics = new ArrayCollection();
        $this->notations = new ArrayCollection();
        $this->media = new ArrayCollection();
        $this->gameGroups = new ArrayCollection();
    }

    
    public function __toString() {
        return $this->title;
    }

    public function getId(): ?int
    {
        return $this->id;
    }
    // Fix EasyAdmin:
    public function setId(int $id): self
    {
        $this->id = $id;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getEditor(): ?string
    {
        return $this->editor;
    }

    public function setEditor(string $editor): self
    {
        $this->editor = $editor;

        return $this;
    }

    public function getPublishDate(): ?\DateTimeInterface
    {
        return $this->publish_date;
    }

    public function setPublishDate(\DateTimeInterface $publish_date): self
    {
        $this->publish_date = $publish_date;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getColor(): ?string
    {
        return $this->color;
    }

    public function setColor(string $color): self
    {
        $this->color = $color;

        return $this;
    }

    public function getGenre(): ?Genre
    {
        return $this->genre;
    }

    public function setGenre(?Genre $genre): self
    {
        $this->genre = $genre;

        return $this;
    }

    public function getLogo(): ?string
    {
        return $this->logo;
    }

    public function setLogo(?string $logo): self
    {
        $this->logo = $logo;

        return $this;
    }

    public function getBanner(): ?string
    {
        return $this->banner;
    }

    public function setBanner(?string $banner): self
    {
        $this->banner = $banner;

        return $this;
    }

    public function getFontColor(): ?string
    {
        return $this->fontColor;
    }

    public function setFontColor(?string $fontColor): self
    {
        $this->fontColor = $fontColor;

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getFavUsers(): Collection
    {
        return $this->favUsers;
    }

    public function addFavUser(User $favUser): self
    {
        if (!$this->favUsers->contains($favUser)) {
            $this->favUsers->add($favUser);
            $favUser->addFavori($this);
        }

        return $this;
    }

    public function removeFavUser(User $favUser): self
    {
        if ($this->favUsers->removeElement($favUser)) {
            $favUser->removeFavori($this);
        }

        return $this;
    }


    // J'ai "raté" ici le nom donné à la fin de la création de la relation ducoup tout remplacé à la mano
    /**
     * @return Collection<int, Topic>
     */
    public function getTopics(): Collection
    {

        return $this->topics;
    }

    // /**
    //  * @return Collection<int, Topic>
    //  */
    // public function getTopicsDesc(): Collection
    // {
    //     // OrderBy PublishDate:

    //     return $this->createQueryBuilder('t')
    //         ->where('t.game = :game')
    //         ->setParameter('game', 1)
    //         ->orderBy('t.publish_date', 'DESC')
    //         ->getQuery()
    //         ->getResult();
    // }

    public function addTopic(Topic $topic): self
    {
        if (!$this->topics->contains($topic)) {
            $this->topics->add($topic);
            $topic->setGame($this);
        }

        return $this;
    }

    public function removeTopic(Topic $topic): self
    {
        if ($this->topics->removeElement($topic)) {
            // set the owning side to null (unless already changed)
            if ($topic->getGame() === $this) {
                $topic->setGame(null);
            }
        }

        return $this;
    }

    public function getTinyLogo(): ?string
    {
        return $this->tinyLogo;
    }

    public function setTinyLogo(?string $tinyLogo): self
    {
        $this->tinyLogo = $tinyLogo;

        return $this;
    }

    /**
     * @return Collection<int, Notation>
     */
    public function getNotations(): Collection
    {
        return $this->notations;
    }

    public function addNotation(Notation $notation): self
    {
        if (!$this->notations->contains($notation)) {
            $this->notations->add($notation);
            $notation->setGame($this);
        }

        return $this;
    }

    public function removeNotation(Notation $notation): self
    {
        if ($this->notations->removeElement($notation)) {
            // set the owning side to null (unless already changed)
            if ($notation->getGame() === $this) {
                $notation->setGame(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Media>
     */
    public function getMedia(): Collection
    {
        return $this->media;
    }

    public function addMedium(Media $medium): self
    {
        if (!$this->media->contains($medium)) {
            $this->media->add($medium);
            $medium->setGame($this);
        }

        return $this;
    }

    public function removeMedium(Media $medium): self
    {
        if ($this->media->removeElement($medium)) {
            // set the owning side to null (unless already changed)
            if ($medium->getGame() === $this) {
                $medium->setGame(null);
            }
        }

        return $this;
    }

    public function getSubBanner(): ?string
    {
        return $this->subBanner;
    }

    public function setSubBanner(?string $subBanner): self
    {
        $this->subBanner = $subBanner;

        return $this;
    }

    /**
     * @return Collection<int, Group>
     */
    public function getGameGroups(): Collection
    {
        return $this->gameGroups;
    }

    public function addGameGroup(Group $gameGroup): self
    {
        if (!$this->gameGroups->contains($gameGroup)) {
            $this->gameGroups->add($gameGroup);
            $gameGroup->setGame($this);
        }

        return $this;
    }

    public function removeGameGroup(Group $gameGroup): self
    {
        if ($this->gameGroups->removeElement($gameGroup)) {
            // set the owning side to null (unless already changed)
            if ($gameGroup->getGame() === $this) {

src/Entity/Media.php
<?php

namespace App\Entity;

use App\Repository\MediaRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation\Slug;

#[ORM\Entity(repositoryClass: MediaRepository::class)]
class Media
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $publish_date = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $url = null;

    #[ORM\Column(length: 50)]
    private ?string $status = null;

    #[ORM\Column(length: 50)]
    private ?string $validated = null;

    #[ORM\ManyToOne(inversedBy: 'media')]
    private ?User $user = null;

    #[ORM\ManyToOne(inversedBy: 'media')]
    private ?Game $game = null;

    #[ORM\OneToMany(mappedBy: 'media', targetEntity: MediaPost::class, cascade: ["remove"])]
    private Collection $mediaPosts;

    #[ORM\JoinTable(name: 'media_upvotes')]
    #[ORM\ManyToMany(targetEntity: User::class)]
    private Collection $userUpvote;

    #[ORM\Column(length: 255, unique: true)]
    #[Slug(fields: ['title'])]
    private ?string $slug = null;

    public function __construct()
    {
        $this->mediaPosts = new ArrayCollection();
        $this->userUpvote = new ArrayCollection();
    }

    
    public function __toString() {
        return $this->title;
    }

    public function getId(): ?int
    {
        return $this->id;
    }
    // Fix EasyAdmin:
    public function setId(int $id): self
    {
        $this->id = $id;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getPublishDate(): ?\DateTimeInterface
    {
        return $this->publish_date;
    }

    public function setPublishDate(\DateTimeInterface $publish_date): self
    {
        $this->publish_date = $publish_date;

        return $this;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(?string $url): self
    {
        $this->url = $url;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getValidated(): ?string
    {
        return $this->validated;
    }

    public function setValidated(string $validated): self
    {
        $this->validated = $validated;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getGame(): ?Game
    {
        return $this->game;
    }

    public function setGame(?Game $game): self
    {
        $this->game = $game;

        return $this;
    }

    // public function getExtension(): ?string {

    //     return $this->getUrl();
    // }

    /**
     * @return Collection<int, MediaPost>
     */
    public function getMediaPosts(): Collection
    {
        return $this->mediaPosts;
    }

    // Pas mappé
    public function getMediaPostsCount(): ?int
    {
        return count($this->mediaPosts);
    }
    

    public function addMediaPost(MediaPost $mediaPost): self
    {
        if (!$this->mediaPosts->contains($mediaPost)) {
            $this->mediaPosts->add($mediaPost);
            $mediaPost->setMedia($this);
        }

        return $this;
    }

    public function removeMediaPost(MediaPost $mediaPost): self
    {
        if ($this->mediaPosts->removeElement($mediaPost)) {
            // set the owning side to null (unless already changed)
            if ($mediaPost->getMedia() === $this) {
                $mediaPost->setMedia(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getUserUpvote(): Collection
    {
        return $this->userUpvote;
    }

    // Nombre de likes du Média 
    // Twig: {{ media.upvoteCount }} (pas de proriété, juste fonction)
    public function getUpvoteCount(): int
    {
        return count($this->userUpvote);
    }

    public function addUserUpvote(User $userUpvote): self
    {
        if (!$this->userUpvote->contains($userUpvote)) {
            $this->userUpvote->add($userUpvote);
        }

        return $this;
    }

    public function removeUserUpvote(User $userUpvote): self
    {
        $this->userUpvote->removeElement($userUpvote);

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }
}

templates/user/allMediasUser.html.twig
{% extends 'base.html.twig' %}

{% block title %}Médias publiés{% endblock %}
{% block meta_description %}
    Liste de vos médias publiés
{% endblock %}

{% block body %}


    <header class="globalBanner" style="background: url('{{ asset('img/banner1.jpg') }}' )">
        <a href="{{ path('app_home') }}"><img src="{{ asset('img/logoSquadForge_v3.png') }}" class="logoPng" id="logoPng" alt='bearded dwarf forging a sword above "SquadForge" title' /></a>
        <nav id="navLine" class="navLine">
            <span id="closeBurgerMobile"><i class="fa-solid fa-xmark"></i></span>
            <a href="{{ path('app_home') }}" class="homeNav navActive"><i class="fa-solid fa-house"></i></a>
            <a href="{{ path('app_games') }}" class="gamesNav caps">jeux</a>
            {% if app.user %}
                <a href="{{ path('app_userGroups') }}" class="teamsNav caps">teams</a>
                <a href="{{ path('app_showNotifsList') }}" class="notifsNav" style="padding:0;">
                    <div class="navNotifDiv">
                        <i class="fa-solid fa-bell notifBell"></i>
                        {% if userNotifCount > 0 %}
                            <span class="newNotifBubbleCount bubleNotif" id="newNotifBubbleCount">{{ userNotifCount }}</span>
                        {% endif %}
                    </div>
                </a>
            {% else %}
                <a href="{{ path('app_allGroupList') }}" class="teamsNav caps">teams</a>
            {% endif %}
            {% if app.user and "ROLE_MODO" in app.user.roles %}
            
                <a href="{{ path('app_moderationDashboard') }}" id="modoNav" class="modoNav">
                    <div class="modoNavSubDiv">
                        <span>Modération</span>
                        {% if modoNotifValidationCount > 0 %}
                            <span class="newNotifBubbleCount bubleModo1">{{ modoNotifValidationCount }}</span>
                        {% endif %}
                        {% if modoNotifReportCount > 0 %}
                            <span class="newNotifBubbleCount bubleModo2">{{ modoNotifReportCount }}</span>
                        {% endif %}
                    </div>
                </a>

                <script>
                    // Ajout d'espace libre sur l'onglet Nav "Modération" si bulles (car bulles absolutes)
                    var paddingRightOnglet = 0;
                    if({{modoNotifValidationCount}} > 0) {
                        paddingRightOnglet += 17;
                    }
                    if({{modoNotifReportCount}} > 0) {
                        paddingRightOnglet += 17;
                    }
                    document.getElementById('modoNav').style.paddingRight = paddingRightOnglet + "px";
                </script>

            {% endif %}

            {# Profil + deco #}
            <div id="profilBurgerMobile">
                {% if app.user %}
                    <a href="{{ path('app_user') }}" class="profil" id="profilBtnNav"><i class="fa-solid fa-user profilIcon"></i>  {{ app.user.pseudo|capitalize }}</a>
                    <a href="{{ path('app_logout') }}" class="decoBtn"><i class="fa-solid fa-power-off decoBtnMobile"></i></a>
                {% else %}
                    <a href="{{ path('app_login') }}" class="profil" id="loginBtnNav" style="border-right:2px solid #80808061">Connexion</a>
                    <a href="{{ path('app_register') }}" class="profil" id="registerBtnNav" style="border-bottom-left-radius:0px;">S'inscrire</a>
                {% endif %}
            </div>

        </nav>

        {# Show menu Burger (mobile) #}
        <span id="showBurgerMenu"><i class="fa-solid fa-bars"></i></span>

    </header>
    
    {# HeaderSouligne + Bandeau avertissement muted #}
    {% if app.user and app.user.muted and time_diff_future(app.user.endDateStatus) != false %}
        <div class="headerUnderline"></div>
        <div class="mutedBanner">  
            <span><i class="fa-solid fa-circle-exclamation mutedBannerIcon"></i>Vous êtes actuellement réduit au silence <span class="muteEndDate">( fin dans <span class="strongNbr">{{ time_diff_future(app.user.endDateStatus) }}</span> )</span></span>
        </div>
    {% else %}
        <div class="headerUnderline marginBottomHeaderLine"></div>
    {% endif %}


    <main class="main">

        {# Fil d'Ariane #}
        <p class="breadcrumbs">
            <a  href="{{ path('app_home') }}"><i class="fa-solid fa-house arianeHome"></i></a>
            <i class="fa-solid fa-angle-right arianeArrow"></i>
            <a class="underlineLink" href="{{ path('app_user') }}">Mon compte</a>
            <i class="fa-solid fa-angle-right arianeArrow"></i>
            <span>Mes Médias<span>
        </p>

        <section>

            <h2 class="pageTitle">Médias publiés <span class="gameListCount">({{ userMediasCount }})</span></h2>

            <div class="listContainer topicList listMarginTop">

                {% set index = 0 %}

                {% for media in userMedias %}

                    {% if app.user and app.user.autoPlayGifs %}
                    <a class="mediaBigCardLink" href="{{ path('app_mediaDetail', {'slug': media.slug}) }}">
                    {% endif %}
                        
                        <article class="mediaCard" style="background-color:{{ media.game.color }};">

                            {% if app.user and not app.user.autoPlayGifs %}
                            <a href="{{ path('app_mediaDetail', {'slug': media.slug}) }}">
                            {% endif %}
                            <div class="mediaCardHeader" style="border-bottom: 3px solid {{ media.game.color }}">
                                <div class="tinyLogoDiv">
                                    <img class="tinyLogoMedia" src="{{ asset('img/games/tinyLogo/' ~ media.game.tinyLogo) }}" alt="logo du jeu {{ media.game.title }}" />
                                </div>
                                <span class="mediaTitle">{{ media.title|capitalize }}</span>
                                {# Sticker NEW #}
                                {% if app.user and media.publishDate > app.user.previousCo %}
                                    <span class="stickerNew stickerNewMedia stickerNewMediaDetail" style="color: {{ media.game.color }}"><i class="fa-solid fa-fire fa-beat-fade"></i> new</span>
                                {% endif %}
                                {# <span class="mediaCardPublishDate">{{ time_diff(media.publishDate) }}</span> #}
                                <div id="deleteSelfMediaDiv{{index}}" class="deleteSelfMediaDiv" title="Supprimer le média"><i class="fa-solid fa-trash deleteSelfMediaIcon"></i></div>
                            </div>
                            {% if app.user and not app.user.autoPlayGifs %}
                            </a>
                            {% endif %}

                            {# Gif autoplay=false si paramètre user #}
                            {% if app.user %}
                                {% if not app.user.autoPlayGifs %}
                                    <img data-gifffer="{{ asset("img/uploads/" ~ media.url) }}" data-gifffer-alt="media" class="mediaImg" />
                                {% else %}
                                    <img src="{{ asset("img/uploads/" ~ media.url) }}" alt="media" class="mediaImg" />
                                {% endif %}
                            {% else %}
                            <a href="{{ path('app_mediaDetail', {'slug': media.slug}) }}">
                                <img src="{{ asset("img/uploads/" ~ media.url) }}" alt="media" class="mediaImg" />
                            </a>
                            {% endif %}
                            
                        </article>

                    {% if app.user and app.user.autoPlayGifs %}
                    </a>
                    {% endif %}


                    {# Upvote/downvote média + score + nbrPosts #}
                    <div class="mediaCardStatsDiv">

                        {# Upvote/downvote média + score + nbrPosts #}
                        {# Pas opti: bloucle sur tous les likes du post pour savoir si liké (boucle dans boucle) #}
                        {% set liked = "" %}
                        
                        {% if app.user %}
                            {% for upvote in media.UserUpvote %}
                                {% if upvote == app.user %}
                                    {% set liked = "upBtnLiked" %}
                                {% endif %}
                            {% endfor %}
                        {% endif %}

                        <div class="inline mediaSubLikeDiv" mediaId={{ media.id }}>
                            <span id="countLikesMedia{{ media.id }}" value="{{ media.upvoteCount }}"> {{ media.upvoteCount }} </span>
                            <i mediaId={{ media.id }} class="likeMedia fa-regular fa-circle-up {{ liked }}"></i>
                        </div>
                    
                        {% if media.mediaPostsCount == 0 %}
                            <a href="{{ path('app_mediaDetail', {'slug':media.slug}) }}" class="mediaSubPostsDiv">
                                <div class="inline" style="opacity:0.7;">
                                    {{ media.mediaPostsCount }} 
                                    <i class="fa-solid fa-message msgIconColorGreyed"></i>
                                </div>
                            </a>
                        {% else %}
                            <a href="{{ path('app_mediaDetail', {'slug':media.slug}) }}" class="mediaSubPostsDiv">
                                <div class="inline">
                                    {{ media.mediaPostsCount }} 
                                    <i class="fa-solid fa-message msgIconColor"></i>
                                </div>
                            </a>
                        {% endif %}

                    </div>


                    <div style="width:35%; margin: 15px auto; height:1px; background-color: {{ media.game.color }}; opacity:0.4;"></div>


                    <dialog class="modalDialog" id="confirmDeleteSelfMediaModal{{index}}">
                        <p style="font-size:1.3em;">Êtes-vous sûr de vouloir supprimer ce média ? <br>Tout les commentaires associés seront également supprimés</p>

                        <a href="{{ path('app_deleteSelfMedia',{'idMedia':media.id}) }}" class="confirmModal">Supprimer</a>
                        <span id="cancelDeleteSelfMedia{{index}}" class="cancelModal" onclick="confirmDeleteSelfMediaModal{{index}}.close()">Annuler</span>                            
                    </dialog>


                    <script>
                        document.getElementById('deleteSelfMediaDiv{{index}}').addEventListener('click', function() {
                            // Evite le click sur le lien de la div parente:
                            event.preventDefault();
                            // Modal confirmation
                            document.getElementById('confirmDeleteSelfMediaModal{{index}}').showModal();
                        })
                    </script>

                    {% set index = index + 1 %}

                {% endfor %}

            </div>

        </section>

    </main>

{% endblock %}